name: dis-res
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests
  - pip
  - mlflow
  - hydra-core
  - jupyter
  - jupyterlab
  - scikit-learn
  - scipy
  - numpy
  - pandas
  - pandas-datareader
  - matplotlib
  - seaborn
  - nltk
  - numba
  - tqdm
  - pip:
      - protobuf
      - chardet
      - hydra-joblib-launcher
      - wandb
      - autopep8
      - joblib
      - pytest
      - setuptools
      - wheel