name: dis-res
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.16
  - requests
  - pip
  - jupyter
  - jupyterlab
  - scikit-learn
  - scipy
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - nltk
  - numba
  - tqdm
  - flask
  - flask-wtf
  - pip:
      - protobuf
      - chardet
      - autopep8
      - joblib
      - pytest
      - setuptools
      - flake8
      - pylint
      - pydantic
      - sqlalchemy<2.0
      - wheel
      - Flask-SQLAlchemy
      - Flask-Migrate